services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
    command: ["nginx", "-g", "daemon off;"]

  api1:
    image: g4brielv/rinha-backend-2025:standard
    #build: .
    container_name: rinha-api-1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Xms54m -Xmx54m -XX:MaxMetaspaceSize=80m #Xms (Memory start), Xmx (Max memory), MaxMetaspaceSize (Max metadata size)
    depends_on:
      postgresql-rinha:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend
      - payment-processor
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "135MB"

  api2:
    image: g4brielv/rinha-backend-2025:standard
    #build: .
    container_name: rinha-api-2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Xms54m -Xmx54m -XX:MaxMetaspaceSize=80m #Xms (Memory start), Xmx (Max memory), MaxMetaspaceSize (Max metadata size)
    depends_on:
      postgresql-rinha:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend
      - payment-processor
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "135MB"

  postgresql-rinha:
    image: postgres:16-alpine
    container_name: rinha-postgresql
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "70MB"

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

