services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "40MB"
    command: ["nginx", "-g", "daemon off;"]

  api1:
    image: g4brielv/rinha-backend-2025:pos-rinha
    #build: .
    container_name: rinha-api-1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- JAVA_TOOL_OPTIONS
    depends_on:
      - redis-rinha
    env_file:
      - .env
    networks:
      - backend
      - payment-processor
    ports:
      - "8081:8080"
#    healthcheck:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "105MB"

  api2:
    image: g4brielv/rinha-backend-2025:pos-rinha
    #build: .
    container_name: rinha-api-2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- JAVA_TOOL_OPTIONS
    depends_on:
      - redis-rinha
    env_file:
      - .env
    networks:
      - backend
      - payment-processor
    ports:
      - "8082:8080"
#    healthcheck:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "105MB"

  redis-rinha:
    image: redis:7-alpine
    container_name: rinha-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
        --save ""
        --appendonly no
        --maxclients 5000
        --protected-mode no
        --hz 10
    volumes:
        - redis_data:/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

